### ISSUE TITLE
5. Docker Swarm & Kubernetes Cluster

### ISSUE THREAD

**Issue by Krishnamurtyp** [Training-and-Development-SRE/Deliverables#1]

**Comment by Prakash-SRE** [comment]
[Swarm Compose Kubernetes.docx](https://github.com/Training-and-Development-SRE/Deliverables/files/5761608/Swarm.Compose.Kubernetes.docx)
[DockerSwarm.pptx](https://github.com/Training-and-Development-SRE/Deliverables/files/5761609/DockerSwarm.pptx)

SWARM Demo and Comparision between Compose/Swarm/Kubernetes

**Comment by Prakash-SRE** [comment]
Team:
Prakash
Narayanan
Murali
Siva
Kumar

**Comment by Krishnamurtyp** [comment]
Thank you guys

Krishna Murthy

**Comment by Prakash-SRE** [comment]
[Networking Overview.docx](https://github.com/Training-and-Development-SRE/Deliverables/files/5763363/Networking.Overview.docx)

Base overview of Networking
