### ISSUE TITLE
002. Docker Security & Networking

### ISSUE THREAD

**Issue by Krishnamurtyp** [Training-and-Development-SRE/Deliverables#4]

**Comment by skumarkuppil** [comment]
[Docker Security_v1.pptx](https://github.com/Training-and-Development-SRE/Deliverables/files/5748467/Docker.Security_v1.pptx)

**Comment by skumarkuppil** [comment]
Container Security Presentation

**Comment by Krishnamurtyp** [comment]
Many thanks ...for efforts and this work
